#!/bin/bash

export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )" 

sudo apt-get update
sudo apt-get install --assume-yes \
wget \
curl \
git  \
vifm \
zsh  \
apt-transport-https \
ca-certificates \
gnupg \
lsb-release \
fonts-firacode \
mlocate \
net-tools \
openssh-server \
htop \
fd-find \
silversearcher-ag

# zsh
sudo apt-get install --assume-yes zsh
if [[ ! -d $HOME/.oh-my-zsh ]]; then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
  ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  cd $ZSH_CUSTOM/plugins && git clone https://github.com/chrissicool/zsh-256color
  cd $SCRIPT_DIR
fi;
ln -s $SCRIPT_DIR/zshrc $HOME/.zshrc -f

# terminator
if ! command -v terminator &> /dev/null; then
  sudo apt-get install -y terminator
  [[ ! -d $HOME/.config/terminator ]] && mkdir $HOME/.config/terminator
  ln -s $SCRIPT_DIR/terminator_config $HOME/.config/terminator/config -f
fi

# tmux
sudo apt-get install --assume-yes tmux
cd $HOME
[ ! -d $HOME/.tmux ] && git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .
cd $SCRIPT_DIR

# ssh
ln -s $SCRIPT_DIR/ssh_config $HOME/.ssh/config -f
ssh-keygen -t rsa -b 4096 -C 'maqsood.ulde@gmail.com' -f $HOME/.ssh/git -N '' <<< n  >/dev/null 2>&1
ssh-keygen -t rsa -b 4096 -C 'maqsood.ulde@gmail.com' -f $HOME/.ssh/id_rsa -N '' <<< n  >/dev/null 2>&1

# vim
sudo apt-get remove --assume-yes 'vim*' >/dev/null 2>&1
sudo apt-get install --assume-yes vim-athena neovim
[ ! -d $HOME/.vim/bundle/Vundle.vim ] && \
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
[ ! -d $HOME/.config/nvim ] && mkdir $HOME/.config/nvim
ln -s $SCRIPT_DIR/vimrc $HOME/.config/nvim/init.vim -f
ln -s $SCRIPT_DIR/vimrc $HOME/.vimrc -f
echo -ne '\n' |  vim +PluginInstall +qall

# fzf
[ ! -d $HOME/.fzf ] && git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
$HOME/.fzf/install --all

# github cli
if [[ ! -f /usr/share/keyrings/githubcli-archive-keyring.gpg ]]; then
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
fi
[ ! -d /etc/apt/sources.list.d/github-cli.list ] && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
sudo apt update
sudo apt install gh

#rvm
if ! command -v rvm &> /dev/null; then
  gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
  curl -sSL https://get.rvm.io | bash -s stable
  rvm install 3.0
  rvm use 3.0
fi

#node
if ! command -v node &> /dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi

# yarn
if ! command -v yarn &> /dev/null; then
  sudo npm install --global yarn
fi

# set inputrc
ln -s $SCRIPT_DIR/inputrc $HOME/.inputrc -f
ln -s $SCRIPT_DIR/editrc $HOME/.editrc -f

# # docker
# sudo apt-get remove docker docker-engine docker.io containerd runc
# if [[ ! -f /usr/share/keyrings/docker-archive-keyring.gpg ]]; then
#   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# fi
# [ ! -d /etc/apt/sources.list.d/docker.list ] && echo \
#   "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
#   $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update
# sudo apt-get install docker-ce docker-ce-cli containerd.io --assume-yes
# sudo groupadd docker -f
# sudo usermod -aG docker $USER
# newgrp docker
# sudo systemctl enable docker.service > /dev/null
# sudo systemctl enable containerd.service > /dev/null

# # docker-compose
# if [[ ! -f /usr/local/bin/docker-compose ]]; then
#   sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#   sudo chmod +x /usr/local/bin/docker-compose
# fi
# if [[ ! -f /etc/bash_completion.d/docker-compose ]]; then
#   sudo curl \
#       -L https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/bash/docker-compose \
#       -o /etc/bash_completion.d/docker-compose
# fi
